apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflows.lyra.example.com
spec:
  group: lyra.example.com
  names:
    kind: Workflow
    listKind: WorkflowList
    plural: workflows
    singular: workflow
    shortNames:
    - wf
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: WorkflowName
      type: string
      description: The name of the associated lyra workflow
      JSONPath: .spec.workflowName
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
    - name: LyraStatus
      type: string
      description: The Lyra status
      JSONPath: .status.Code
    - name: StatusInfo
      type: string
      description: Additional information re the status
      JSONPath: .status.Info
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["workflowName"]
          properties:
            workflowName:
              type: "string"
            refreshTime:
              type: "integer"
              minimum: 1
              maximum: 60  