apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflows.lyra.example.com
spec:
  group: lyra.example.com
  names:
    kind: Workflow
    listKind: WorkflowList
    plural: workflows
    singular: workflow
    shortNames:
    - wf
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
