apiVersion: apps/v1
kind: Deployment
metadata:
  name: lyra-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: lyra-operator
  template:
    metadata:
      labels:
        name: lyra-operator
    spec:
      serviceAccountName: lyra-operator
      containers:
        - name: lyra-operator
          image: lyraproj/lyra-operator
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "256Mi"
              cpu: "128m"          
          ports:
          - containerPort: 60000
            name: metrics
          command: ["lyra", "controller", "--debug"]
          imagePullPolicy: Never
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: lyra
